apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: klage-dittnav
  namespace: klage
  labels:
    team: klage
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "7200"
spec:
  port: 8080
  image: {{ image }}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 80
  liveness:
    path: /isAlive
    initialDelay: 3
  readiness:
    path: /isReady
    initialDelay: 3
  tokenx:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
  prometheus:
    enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: klage-dittnav-api
        - application: klage-kodeverk-api
        - application: nav-dekoratoren
          namespace: personbruker
  ingresses:
    - {{ingress}}
  envFrom:
    - secret: amplitude
    - secret: slack-url
